# 数据源配置
druid:
  url: jdbc:mysql://192.168.13.180:3306/xssspace?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.xss.util.ShowSqlInterceptor
  userName: xsslibe
  password: xssroot
  filters: stat,wall

#redis 配置信息
spring:
  redis:
    # Redis服务器地址
    host: 192.168.13.180
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:
    # Redis数据库索引 指定数据存在哪个数据库（默认为0）
    database: 1
    # 连接超时时间（毫秒）
    timeout: 0
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 500
      # 连接池中的最小空闲连接
      min-idle: 0
# 配置文件可以有 application.yml 和 application.properties 这里使用yml
# mysql 配置 这里 url  username password 与实际使用配置一致
    mvc.throw-exception-if-no-handler-found: true
    resources.add-mappings: false
    datasource:
        type: com.alibaba.druid.pool.DruidDataSource
        driverClassName: com.mysql.jdbc.Driver
        url: jdbc:mysql://192.168.13.180:3306/xssspace?useUnicode=true&characterEncoding=utf8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&statementInterceptors=com.xss.util.ShowSqlInterceptor
        username: xsslibe
        password: xssroot
  # 开启redis缓存session
  session.store-type: redis

  rabbitmq:
      host: 192.168.13.180
      port: 5672
      username: xss
      password: xss
      virtual-host: /



